/**
 * The workbook's machine interface: which sheets exist, and what each column is
 * called.
 *
 * §5.1 makes one decision that shapes this whole file — **sheet and column
 * names are not localized.** The Instructions sheet is translated, the wizard
 * around it is translated, and the header row is English snake_case in both
 * languages. A Korean Team Lead and an English one exchange one workbook, and
 * neither of them has to know which language the other's Excel was installed
 * in.
 *
 * The other decision is that names are exact. The member importer accepts
 * `Email`, `E-mail`, and `이메일` for one column, because that file comes out of
 * a school's own system and Cove has no say in what it looks like. This one is
 * generated by Cove and edited in place: a header that no longer matches means
 * the row was edited by hand into something ambiguous, and §5.1 says an
 * approximate spelling is a rejection rather than a guess.
 *
 * See §5.1 and §5.3–5.6 of the team lead Excel problem import design.
 */

/* --------------------------------------------------------------- sheets */

export const contentImportSheets = [
  "Instructions",
  "Structure",
  "Problems",
  "Test Cases",
  "Hints",
] as const;
export type ContentImportSheet = (typeof contentImportSheets)[number];

/**
 * §5.1 — Hints is the only optional sheet.
 *
 * A course of problems with no hints is an ordinary course. A workbook with no
 * Problems sheet is a file somebody built by hand from the wrong template, and
 * inferring an empty one would preview as "no changes" — the least useful
 * possible answer to "why did nothing import".
 */
export const requiredContentImportSheets: readonly ContentImportSheet[] = [
  "Instructions",
  "Structure",
  "Problems",
  "Test Cases",
];

/* -------------------------------------------------------------- columns */

export const structureColumns = [
  "module_key",
  "module_order",
  "module_title",
  "module_description",
  "lecture_key",
  "lecture_order",
  "lecture_title",
  "lecture_description",
] as const;
export type StructureColumn = (typeof structureColumns)[number];

export const requiredStructureColumns: readonly StructureColumn[] = [
  "module_key",
  "module_title",
  "lecture_key",
  "lecture_title",
];

export const problemColumns = [
  "problem_key",
  "lecture_key",
  "problem_order",
  "title",
  "difficulty",
  "description",
  "description_format",
  "input_format",
  "output_format",
  "constraints",
  "starter_code",
  "ai_feedback_enabled",
] as const;
export type ProblemColumn = (typeof problemColumns)[number];

export const requiredProblemColumns: readonly ProblemColumn[] = [
  "problem_key",
  "lecture_key",
  "title",
  "difficulty",
  "description",
];

export const testCaseColumns = [
  "problem_key",
  "test_order",
  "input",
  "expected_output",
  "visibility",
] as const;
export type TestCaseColumn = (typeof testCaseColumns)[number];

export const requiredTestCaseColumns: readonly TestCaseColumn[] = [
  "problem_key",
  "test_order",
  "expected_output",
  "visibility",
];

export const hintColumns = [
  "problem_key",
  "hint_order",
  "content",
  "trigger_expression",
] as const;
export type HintColumn = (typeof hintColumns)[number];

export const requiredHintColumns: readonly HintColumn[] = [
  "problem_key",
  "hint_order",
  "content",
];

/** Every data sheet's column list, so generation and reading share one source. */
export const contentImportColumns = {
  Structure: structureColumns,
  Problems: problemColumns,
  "Test Cases": testCaseColumns,
  Hints: hintColumns,
} as const;

export const requiredContentImportColumns = {
  Structure: requiredStructureColumns,
  Problems: requiredProblemColumns,
  "Test Cases": requiredTestCaseColumns,
  Hints: requiredHintColumns,
} as const;

export type ContentImportDataSheet = keyof typeof contentImportColumns;

export const contentImportDataSheets = Object.keys(
  contentImportColumns,
) as ContentImportDataSheet[];

/* --------------------------------------------------------------- header */

/**
 * A header cell, reduced enough to survive a spreadsheet round trip.
 *
 * Case and whitespace only. `Module_Key` and `module key` reach the same
 * column because Excel's own autocorrect and a person's shift key produce both,
 * and neither is ambiguous. `module` does not, and neither does `모듈 키`: §5.1
 * refuses to infer a required column from an approximate spelling, because the
 * cost of guessing wrong is importing a column of titles as identities.
 */
export function normalizeColumnName(cell: string): string {
  return cell.normalize("NFKC").trim().toLowerCase().replace(/[\s_]+/g, "_");
}

export type ColumnIndex<Column extends string> = Partial<
  Record<Column, number>
>;

/**
 * Where each known column sits, by name rather than by position.
 *
 * Columns are addressed by name throughout, so a Team Lead who inserts their
 * own `notes` column in the middle of the sheet does not shift every value one
 * place to the right. §5.1 ignores unknown columns and reports them as a
 * warning, which is exactly what "you added something we will not import"
 * should feel like.
 *
 * A duplicate canonical column keeps the *first*, and the caller reports it. Two
 * columns called `problem_key` is a file somebody built by pasting two exports
 * together, and silently preferring the last one imports the half they were not
 * looking at.
 */
export function indexHeaderRow<Column extends string>(
  cells: readonly string[],
  known: readonly Column[],
): { columns: ColumnIndex<Column>; unknown: string[]; duplicated: Column[] } {
  const columns: ColumnIndex<Column> = {};
  const unknown: string[] = [];
  const duplicated: Column[] = [];

  cells.forEach((cell, index) => {
    const normalized = normalizeColumnName(cell);
    if (normalized.length === 0) return;
    const match = known.find((column) => column === normalized);
    if (!match) {
      unknown.push(cell.trim());
      return;
    }
    if (columns[match] !== undefined) {
      if (!duplicated.includes(match)) duplicated.push(match);
      return;
    }
    columns[match] = index;
  });

  return { columns, unknown, duplicated };
}

/** Missing required columns, in the order the template declares them. */
export function missingRequiredColumns<Column extends string>(
  columns: ColumnIndex<Column>,
  required: readonly Column[],
): Column[] {
  return required.filter((column) => columns[column] === undefined);
}

/**
 * One cell, by column name, or the empty string.
 *
 * A sparse row — one where the author cleared the trailing cells — is shorter
 * than the header, and every caller wants "" rather than undefined for that.
 */
export function cellAt<Column extends string>(
  row: readonly string[],
  columns: ColumnIndex<Column>,
  column: Column,
): string {
  const index = columns[column];
  if (index === undefined) return "";
  return row[index] ?? "";
}

/**
 * The `template_version` value, read from the Instructions sheet.
 *
 * The sheet is prose for a person, so the version is found by scanning for the
 * label rather than by reading a fixed cell: an author who adds a paragraph
 * above it must not invalidate their own workbook. The label itself is
 * canonical and untranslated for the same reason the column names are.
 */
export function readTemplateVersion(rows: readonly string[][]): number | null {
  for (const row of rows) {
    const labelIndex = row.findIndex(
      (cell) => normalizeColumnName(cell) === "template_version",
    );
    if (labelIndex === -1) continue;
    for (const cell of row.slice(labelIndex + 1)) {
      const value = cell.trim();
      if (value.length === 0) continue;
      const parsed = Number.parseInt(value, 10);
      return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : null;
    }
  }
  return null;
}
