import type { ExerciseDifficulty, TestCaseVisibility } from "../course.js";

/**
 * Cell values, read strictly.
 *
 * §5.7 is one rule stated four ways: **the importer never guesses.** The v1
 * importer defaulted an unrecognised difficulty to EASY and an unrecognised
 * boolean to false, and both defaults are silent — a Team Lead who typed
 * "Medum" got a working problem with the wrong difficulty and no indication
 * anything had happened. Every function here returns null for input it does not
 * recognise, and null becomes a row issue with the received value printed
 * beside it.
 *
 * The one thing that *is* normalized without complaint is whitespace and line
 * endings, because those are properties of the file rather than of what the
 * author meant. A workbook that has been through Windows carries CRLF; the
 * author did not type it and does not want to see it reported.
 *
 * See §5.7 of the team lead Excel problem import design.
 */

/**
 * A cell, made safe to store and compare.
 *
 * Control characters cannot appear in a title, a description, or Python source
 * and are how a crafted workbook smuggles a line break into a CSV export, so
 * they are stripped. Tab and newline survive — both are meaningful inside
 * starter code, and losing them would corrupt the one column where whitespace
 * is the content.
 *
 * CRLF collapses to LF, per §5.5: expected output compared byte-for-byte
 * against a judge's output has to agree about line endings, and the spreadsheet
 * the author used is not a reliable witness to which one they chose.
 */
export function normalizeCellText(value: string): string {
  return (
    value
      .replace(/\r\n?/g, "\n")
      // Everything below space except tab and newline, plus DEL. Those two
      // survive because they carry meaning inside Python source and test input.
      .replace(/[\u0000-\u0008\u000B-\u001F\u007F]/g, "")
  );
}

/**
 * A cell whose surrounding whitespace carries no meaning.
 *
 * Used for keys, titles, and descriptions. Deliberately *not* used for test
 * input, expected output, or starter code: §5.5 preserves those exactly,
 * because a trailing newline can be the difference between a passing and a
 * failing submission and trimming it would silently change what the author
 * wrote.
 */
export function normalizeTrimmedText(value: string): string {
  return normalizeCellText(value).trim();
}

/** Whether a cell holds nothing a person typed. */
export function isBlankCell(value: string): boolean {
  return normalizeTrimmedText(value).length === 0;
}

/* --------------------------------------------------------------- enums */

const difficultyValues: Record<string, ExerciseDifficulty> = {
  EASY: "EASY",
  MEDIUM: "MEDIUM",
  HARD: "HARD",
};

/**
 * §5.7 — the three canonical values, case-insensitively, and nothing else.
 *
 * No aliases, unlike the member importer's role column. The difference is who
 * writes the file: a member list is exported from a school's own system and
 * arrives saying "학생", while this workbook is generated by Cove and edited in
 * place. Accepting "hard-ish" would only widen what a typo can silently become.
 */
export function normalizeDifficulty(value: string): ExerciseDifficulty | null {
  const cleaned = normalizeTrimmedText(value).toUpperCase();
  return difficultyValues[cleaned] ?? null;
}

const visibilityValues: Record<string, TestCaseVisibility> = {
  SAMPLE: "SAMPLE",
  HIDDEN: "HIDDEN",
};

export function normalizeTestVisibility(
  value: string,
): TestCaseVisibility | null {
  const cleaned = normalizeTrimmedText(value).toUpperCase();
  return visibilityValues[cleaned] ?? null;
}

const descriptionFormats = ["PLAIN_TEXT", "RICH_TEXT_HTML"] as const;
export type ContentImportDescriptionFormat = (typeof descriptionFormats)[number];

export function normalizeDescriptionFormat(
  value: string,
): ContentImportDescriptionFormat | null {
  if (isBlankCell(value)) return "PLAIN_TEXT";
  const cleaned = normalizeTrimmedText(value).toUpperCase();
  return (
    descriptionFormats.find((format) => format === cleaned) ?? null
  );
}

/* ------------------------------------------------------------- booleans */

/**
 * §5.7 — the accepted spellings, in both interface languages.
 *
 * Wider than the enums above because a boolean column is the one a Team Lead
 * fills in by hand across two hundred rows, and `Y` is what a person types when
 * the column is called `ai_feedback_enabled`. Everything outside this list is an
 * error rather than a false: "no thanks" and "N/A" both mean something, and
 * neither of them means what `false` means.
 */
const trueValues = new Set(["true", "y", "yes", "1", "예"]);
const falseValues = new Set(["false", "n", "no", "0", "아니요", "아니오"]);

export function normalizeStrictBoolean(value: string): boolean | null {
  const cleaned = normalizeTrimmedText(value).toLowerCase();
  if (trueValues.has(cleaned)) return true;
  if (falseValues.has(cleaned)) return false;
  return null;
}

/* --------------------------------------------------------------- orders */

/**
 * A position column, or null when the cell is blank.
 *
 * §5.3 gives blank a real meaning — preserve for an existing entity, append for
 * a new one — so "blank" and "unreadable" have to be distinguishable, which is
 * why this returns a small union rather than a nullable number. Collapsing them
 * would make `problem_order: banana` silently append.
 *
 * Excel stores whole numbers as floats, so `3` arrives as `"3"` and sometimes as
 * `"3.0"`. The first is a position; the second is too. `3.5` is not: §5.7 makes
 * a fractional order an error rather than rounding it, because rounding decides
 * which of two problems comes first on the author's behalf.
 */
export type ParsedOrder =
  | { kind: "blank" }
  | { kind: "value"; value: number }
  | { kind: "invalid" };

export function parseOrder(value: string): ParsedOrder {
  const cleaned = normalizeTrimmedText(value);
  if (cleaned.length === 0) return { kind: "blank" };
  if (!/^\d+(?:\.0+)?$/.test(cleaned)) return { kind: "invalid" };
  const parsed = Number.parseInt(cleaned, 10);
  if (!Number.isSafeInteger(parsed) || parsed < 1) return { kind: "invalid" };
  return { kind: "value", value: parsed };
}

/* -------------------------------------------------------------- display */

/**
 * A value, shortened for a table cell and stripped of anything that would
 * escape it.
 *
 * The preview prints values the workbook supplied, which means it prints
 * attacker-supplied text into a page the Team Lead is reading. React escapes
 * the HTML; this handles the other half — newlines and tabs that would break a
 * single-line cell into something that no longer looks like one row.
 */
export function truncateForPreview(value: string, limit: number): string {
  const flattened = value.replace(/\s+/g, " ").trim();
  if (flattened.length <= limit) return flattened;
  return `${flattened.slice(0, limit - 1)}…`;
}

/**
 * §5.7 — whether a cell's *text* begins with a spreadsheet formula prefix.
 *
 * Not the same check as "is this an Excel formula cell": that one belongs to
 * the reader, which can see the `<f>` element and rejects the file outright. A
 * cell whose stored text merely starts with `-` or `=` is left exactly as it
 * is — Python starter code beginning with a negative number is legitimate, and
 * mangling it would break the problem it belongs to. The guard that matters is
 * applied on the way *out*, when a value is written into a CSV a person will
 * open in Excel.
 */
export function startsWithFormulaPrefix(value: string): boolean {
  return /^[=+\-@\t\r]/.test(value);
}
