export const appErrorCodes = [
  "AUTHENTICATION_REQUIRED",
  "TOKEN_INVALID",
  "PROFILE_INCOMPLETE",
  "USER_SUSPENDED",
  "EMAIL_VERIFICATION_REQUIRED",
  "ACADEMY_NOT_FOUND",
  "ACADEMY_MEMBERSHIP_REQUIRED",
  "ACADEMY_MEMBERSHIP_SUSPENDED",
  "PERMISSION_DENIED",
  "INVITATION_INVALID",
  "INVITATION_EXPIRED",
  "INVITATION_EMAIL_MISMATCH",
  "INVITATION_ALREADY_PENDING",
  "JOIN_REQUEST_ALREADY_PENDING",
  "JOIN_REQUEST_NOT_FOUND",
  "JOIN_REQUEST_STATE_CONFLICT",
  "MEMBERSHIP_ALREADY_EXISTS",
  "MEMBERSHIP_STATE_CONFLICT",
  "RATE_LIMITED",
  "OAUTH_ONBOARDING_INTENT_REQUIRED",
  "OAUTH_ONBOARDING_INTENT_INVALID",
  "OAUTH_ONBOARDING_INTENT_EXPIRED",
  "OAUTH_ONBOARDING_INTENT_CONSUMED",
  "OAUTH_PROVIDER_MISMATCH",
  "LAST_MANAGER_REQUIRED",
  "IDENTITY_LINK_CONFLICT",
  "LEGACY_ACCOUNT_ALREADY_MIGRATED",
  "COURSE_NOT_FOUND",
  "COURSE_TITLE_CONFLICT",
  "COURSE_VERSION_NOT_FOUND",
  "COURSE_VERSION_IMMUTABLE",
  "COURSE_DRAFT_ALREADY_EXISTS",
  "CONTENT_PARENT_MISMATCH",
  "CONTENT_POSITION_CONFLICT",
  "CONTENT_VALIDATION_FAILED",
  "EXERCISE_NOT_FOUND",
  "EXERCISE_VALIDATION_FAILED",
  "CONTENT_EDIT_CONFLICT",
  "COURSE_NOT_PUBLISHED",
  "EXERCISE_NOT_AVAILABLE",
  "DRAFT_TOO_LARGE",
  "SUBMISSION_IN_FLIGHT",
  "SUBMISSION_RATE_LIMITED",
  "SUBMISSION_NOT_FOUND",
  "GRADING_UNAVAILABLE",
] as const;

export type AppErrorCode = (typeof appErrorCodes)[number];

const appErrorCodeSet = new Set<string>(appErrorCodes);

export function isAppErrorCode(value: unknown): value is AppErrorCode {
  return typeof value === "string" && appErrorCodeSet.has(value);
}

export const appErrorFallbacks: Record<AppErrorCode, string> = {
  AUTHENTICATION_REQUIRED: "Authentication is required.",
  TOKEN_INVALID: "The session is invalid or expired.",
  PROFILE_INCOMPLETE: "Complete your profile to continue.",
  USER_SUSPENDED: "This account is suspended.",
  EMAIL_VERIFICATION_REQUIRED: "Verify your email to continue.",
  ACADEMY_NOT_FOUND: "The selected academy is not available.",
  ACADEMY_MEMBERSHIP_REQUIRED: "Academy membership is required.",
  ACADEMY_MEMBERSHIP_SUSPENDED: "This academy membership is suspended.",
  PERMISSION_DENIED: "You do not have permission to perform this action.",
  INVITATION_INVALID: "This invitation is invalid.",
  INVITATION_EXPIRED: "This invitation has expired.",
  INVITATION_EMAIL_MISMATCH: "Sign in with the invited email address.",
  INVITATION_ALREADY_PENDING: "An invitation is already pending for this email.",
  JOIN_REQUEST_ALREADY_PENDING: "A join request is already pending.",
  JOIN_REQUEST_NOT_FOUND: "The join request was not found.",
  JOIN_REQUEST_STATE_CONFLICT: "The join request has already been reviewed.",
  MEMBERSHIP_ALREADY_EXISTS: "This user already belongs to the academy.",
  MEMBERSHIP_STATE_CONFLICT: "The membership cannot make that transition.",
  RATE_LIMITED: "Too many requests. Try again later.",
  OAUTH_ONBOARDING_INTENT_REQUIRED: "Choose an academy before social signup.",
  OAUTH_ONBOARDING_INTENT_INVALID: "The social signup request is invalid.",
  OAUTH_ONBOARDING_INTENT_EXPIRED: "The social signup request has expired.",
  OAUTH_ONBOARDING_INTENT_CONSUMED: "The social signup request was already used.",
  OAUTH_PROVIDER_MISMATCH: "The social provider does not match this signup request.",
  LAST_MANAGER_REQUIRED: "The academy must keep at least one active manager.",
  IDENTITY_LINK_CONFLICT: "This identity cannot be linked automatically.",
  LEGACY_ACCOUNT_ALREADY_MIGRATED: "This legacy account is already migrated.",
  COURSE_NOT_FOUND: "The selected course was not found.",
  COURSE_TITLE_CONFLICT: "An active course already uses this title.",
  COURSE_VERSION_NOT_FOUND: "The selected course version was not found.",
  COURSE_VERSION_IMMUTABLE: "Published course content cannot be changed.",
  COURSE_DRAFT_ALREADY_EXISTS: "This course already has an active draft.",
  CONTENT_PARENT_MISMATCH: "The content does not belong to the selected parent.",
  CONTENT_POSITION_CONFLICT: "Two content items cannot use the same position.",
  CONTENT_VALIDATION_FAILED: "Fix the content validation issues and try again.",
  EXERCISE_NOT_FOUND: "The selected programming problem was not found.",
  EXERCISE_VALIDATION_FAILED: "Complete the required problem fields and try again.",
  CONTENT_EDIT_CONFLICT: "This problem changed in another session. Reload it before saving again.",
  COURSE_NOT_PUBLISHED: "This course has no published version yet.",
  EXERCISE_NOT_AVAILABLE: "This problem is not available.",
  DRAFT_TOO_LARGE: "Your code is too large to save.",
  SUBMISSION_IN_FLIGHT: "This problem is already being graded. Wait for the result.",
  SUBMISSION_RATE_LIMITED: "Too many submissions. Wait a moment and try again.",
  SUBMISSION_NOT_FOUND: "That submission was not found.",
  GRADING_UNAVAILABLE: "Grading is temporarily unavailable. Your code is saved.",
};
